INSERT INTO users (user_id, login, pass, firstname, lastname, share, phone, email, permissions, aavso_id, ftp_login, ftp_pass, pass_d) VALUES (1, 'user1', 'pass1', 'Jan', 'Kowalski', 85580, '', 'jan.kowalski@example.com', 1, 'ABCD', 'ABCD', '1234abcd', '1234567890abcdef');
INSERT INTO users (user_id, login, pass, firstname, lastname, share, phone, email, permissions, aavso_id, ftp_login, ftp_pass, pass_d) VALUES (2, 'user2', 'pass2', 'John', 'Doe', 85580, '', 'john.doe@example.com', 1, 'ABCD', 'ABCD', '1234abcd', '1234567890abcdef');


INSERT INTO task_states (id, name, descr) VALUES (0, 'TEMPLATE', 'template');
INSERT INTO task_states (id, name, descr) VALUES (1, 'NEW', 'new');


INSERT INTO telescopes (scope_id, name, descr, min_dec, max_dec) VALUES (1, 'test-scope', 'just a test', -20, 90);
INSERT INTO telescopes (scope_id, name, descr, min_dec, max_dec) VALUES (2, 'test-scope2', 'another test', -20, 90);
